name: dart_cookbook

environment:
  sdk: '>=2.12.0 <3.7.0'

dependencies:
  yaml: any
  yaml_edit: ^2.1.0

dev_dependencies:
  commitlint_cli: 0.4.1
  flutter_lints: 1.0.0
  husky: 0.1.6
  lint_staged: 0.3.0
  melos: 3.1.0

lint_staged:
  'packages/**.dart': dart fix --apply