name: flodash
description: A dart implementation of the popular JavaScript library lodash
version: 0.0.1-dev.1
homepage:

environment:
  sdk: ">=2.12.0 <3.7.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  husky: 0.1.3

flutter:
