name: enhanced_http_example
description: An example project which implements the enhanced_http package
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  cached_network_image: 3.2.3
  enhanced_http:
    path: ../

flutter:
  uses-material-design: true